/*********************************************************************
** Program name: Lab 2
** Author: Jordan Hamilton
** Date: 10/06/2018
** Description: This program prompts the user to enter a valid
** file name, using a file stream object to read the contents of the
** provided file. The frequency of each letter on a line in the file
** is stored in an array of integers, then the user is prompted to
** enter a file name for saving the formatted contents of the array.
** This process is repeated in a while loop for each line detected in
** the input file.
*********************************************************************/

#include <iostream>
#include <fstream>
#include <string>

#include "count_letters.hpp"
#include "output_letters.hpp"

using std::cin;
using std::cout;
using std::endl;
using std::ifstream;
using std::ofstream;
using std::string;

/***********************************************************************************************
** Description: This program can be run via the lab2 executable generated by make.
***********************************************************************************************/
int main() {

  const int ARRAY_SIZE = 26;
  int count[ARRAY_SIZE];
  ifstream inputFile;
  ofstream outputFile;
  string inFileName, outFileName;

  std::cout << "Letter frequency calculator" << endl;

  do {
    std::cout << "Please enter the name of a file to read:" << endl;
    getline(cin, inFileName);
    inputFile.open(inFileName);
  } while (!inputFile);

  while (!inputFile.eof()) {
    count_letters(inputFile, count);
    std::cout << "Paragraph evaluated." << endl;
    std::cout << "Please enter a filename to save the results:" << endl;
    getline(cin, outFileName);
    outputFile.open(outFileName);
    output_letters(outputFile, count);
    outputFile.close();
  }

  inputFile.close();

  return 0;
  
}
